### ISSUE TITLE
Don't want Login to be a popup

### ISSUE THREAD

**Issue by apablado** [danilobuerger/redux-implicit-oauth2#10]
Is there a way to configure the Login as a redirect and not as pop up?

**Comment by danilobuerger** [comment]
Not at the moment. Whats your use case? If you did do a redirect, wouldnt you loose all your redux state?

**Comment by apablado** [comment]
For this particular UC this is not an issue, because the actual application starts after de login.

**Comment by danilobuerger** [comment]
I don't see this as a great fit for this library.
