### ISSUE TITLE
access_token not returned from localstorage

### ISSUE THREAD

**Issue by DraconPern** [danilobuerger/redux-implicit-oauth2#12]
in token.js getToken() doesn't return a token properly because EXPIRES_AT_KEY isn't set right/checked because of null vs ''.

**Comment by danilobuerger** [comment]
@DraconPern could you try with master, it should be fixed there already and please report back. I just didn't do a release yet.

**Comment by danilobuerger** [comment]
@DraconPern did you have a chance to try it out with master or the new release?

**Comment by danilobuerger** [comment]
No response, closing.
