### ISSUE TITLE
It is possible use oauth2 if server has another url?

### ISSUE THREAD

**Issue by BesyadaV** [danilobuerger/redux-implicit-oauth2#16]
Currently i have front runs on localhost:1234/
but my requirements for oauth2 is:
{
response_type: token
client_id: octes
state: hsadjksahdjksahdjksahdjkhsadjkhsakjd
redirect_uri: http://octes/oauth/callback
scope: openid profile email
}
it is possible to use? If yes, how?  plz provide example if it is not a problem.

**Comment by danilobuerger** [comment]
Did you take a look at the example at https://github.com/danilobuerger/redux-implicit-oauth2#example-with-react ? What doesn't work? You can set your oauth2 url to anything you like in `config.url` as shown in the example

**Comment by BesyadaV** [comment]
Sorry, this is was my fail!
And 1 more question. It is posible to make callback(or promises) on Login and Logout function?

**Comment by danilobuerger** [comment]
They are just normal redux actions and you can do with them what you can do with any other action

**Comment by BesyadaV** [comment]
thanks.
