### ISSUE TITLE
Make response type configurable

### ISSUE THREAD

**Issue by dignifiedquire** [danilobuerger/redux-implicit-oauth2#2]
Hey I'm trying to use this with an api where the `reponse_type` sent needs to be set as `code` not `token`. Would be great if this was configurable.

**Comment by danilobuerger** [comment]
Hi @dignifiedquire 

This library only covers the Implicit Grant type. What you want is the Authorization Code Grant type which is out of scope for this library.

I don't know your use case, however, be aware that the Authorization Code Grant is optimized for confidential clients. Mose likely, if you are using react / redux you won't have a confidential client, but a public one. Thus the emphasis on the Implicit Grant type which is optimized for public clients.

**Comment by dignifiedquire** [comment]
Thank you for the quick response. I just realised this myself, and switched to  https://github.com/mulesoft/js-client-oauth2 directly which covers all my bases :)
