### ISSUE TITLE
Property in store to mark as "authentication in progress"

### ISSUE THREAD

**Issue by bcongdon** [danilobuerger/redux-implicit-oauth2#6]
There's currently no way to tell by the state of the store if authentication is in progress.

You can infer by 'isLoggedIn' and 'error', but this leaves discrepancies. For example, if you fail an authentication and then fail again, there's no way to tell when the second failure has occurred.

**Comment by danilobuerger** [comment]
Hi, @bcongdon. Thank you for the PR, I really appreciate it.
Please change `isAuthenticating` to `isLoggingIn`. The reasoning behind this: With OAuth2 we are not really authenticating but authorizing. I didn't want to expose this terminology to the user of this library before, so `isLoggingIn` seems like a better fit.

Also, please set this state on all actions (i.e. `LOGOUT`).

**Comment by bcongdon** [comment]
Ah, good idea. `isLoggingIn` sounds like a better property name. I updated the PR with these changes.

**Comment by danilobuerger** [comment]
I actually wanted to write that in the PR not the issue 😂. Thanks again!
Fixed by #8.
